# Uses Scheduled Triggers, which aren't supported in YAML yet.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml#scheduled

# Daily Tests for Blazor
# These use Sauce Labs resources, hence they run daily rather than per-commit.

# The only Daily Tests we have run in Sauce Labs and only need to run on one machine (because they just trigger SauceLabs)
# Hence we use the 'default-build.yml' template because it represents a single phase
variables:
  SAUCE_CONNECT_DOWNLOAD_ON_INSTALL: true
  E2ETESTS_SauceTest: true
  E2ETESTS_Sauce__TunnelIdentifier: 'blazor-e2e-sc-proxy-tunnel'
  E2ETESTS_Sauce__HostName: 'sauce.local'
jobs:
- template: jobs/default-build.yml
  parameters:
    buildDirectory: src/Components
    buildArgs: -test
    isTestingJob: true
    agentOs: Windows
    jobName: BlazorDailyTests_macOS_Chrome
    jobDisplayName: "Blazor Daily Tests (macOS/Chrome)"
    variables:
      E2ETESTS_Sauce__TestName: 'Blazor Daily Tests - macOS/Chrome'
      E2ETESTS_Sauce__Platform: 'macOS 10.13'
      E2ETESTS_Sauce__BrowserName: 'Chrome'
      E2ETESTS_Sauce__Browserversion: 'latest'
    env:
      # Secrets need to be explicitly mapped to env variables.
      E2ETESTS_Sauce__Username: $(asplab-sauce-labs-username)
      E2ETESTS_Sauce__AccessKey: $(asplab-sauce-labs-access-key)
    artifacts:
    - name: Windows_Logs
      path: ../../artifacts/log/
      publishOnError: true
